# Generated by ./modules/apps/builder/generate_app_variables.sh; DO NOT EDIT.
# Make changes to the template in ./modules/apps/builder/generate_app_variables.sh

locals {
  data = merge(
    {
      command : local.command
      image : local.image,
      name : local.name,
      networks : local.networks
      restart : local.restart
      stop_grace_period : local.stop_grace_period
      volumes : local.volumes
      working_dir : local.working_dir
      configs : local.configs
      ports : [
        for port in local.ports :
        "${port.host_port}:${port.container_port}"
      ],
      environment : [
        for env_key, env_value in local.environment :
        "${env_key}=${env_value}"
      ]
    },
    length(local.entrypoint) > 0 ? { entrypoint : local.entrypoint } : {},
    local.healthcheck != {} ? { healthcheck : local.healthcheck } : {},
  )
}

output "data" {
  value = local.data
}

output "name" {
  value = local.name
}

output "restart" {
  value = local.restart
}

output "environment" {
  value = local.environment
}

output "networks" {
  value = local.networks
}

output "command" {
  value = local.command
}

output "stop_grace_period" {
  value = local.stop_grace_period
}

output "entrypoint" {
  value = local.entrypoint
}

output "working_dir" {
  value = local.working_dir
}

output "healthcheck" {
  value = local.healthcheck
}

output "ports" {
  value = local.ports
}

output "volumes" {
  value = local.volumes
}

output "configs" {
  value = local.configs
}
