# Generated by ./modules/apps/builder/generate_app_variables.sh; DO NOT EDIT.
# Make changes to the template in ./modules/apps/builder/generate_app_variables.sh

variable "name" {
  type        = string
  description = "Name of the service"
}

variable "restart" {
  type        = string
  default     = "on-failure"
  description = "Restart policy"
}

variable "environment" {
  type        = map(string)
  default     = {}
  description = "Environment variables"
}

variable "networks" {
  type        = list(string)
  default     = []
  description = "Networks to connect to"
}

variable "command" {
  type        = list(string)
  default     = []
  description = "Command to run"
}

variable "stop_grace_period" {
  type        = string
  default     = "10s"
  description = "Stop grace period"
}

variable "entrypoint" {
  type        = list(string)
  default     = []
  description = "Entrypoint to run"
}

variable "working_dir" {
  type        = string
  default     = ""
  description = "Working directory"
}

variable "healthcheck" {
  type        = map(string)
  default     = {}
  description = "Healthcheck"
}

variable "ports" {
  type        = list(object({ host_port = number, container_port = number }))
  default     = []
  description = "Ports to expose"
}

variable "volumes" {
  type        = list(object({ mount_name = optional(string), container_path = string, abs_host_path = optional(string) }))
  default     = []
  description = "Volumes to mount"
}

variable "configs" {
  type        = list(object({ config_file = string, destination = string, args = optional(map(string)) }))
  default     = []
  description = "The configs to use for the container"
}
