# Generated by ./modules/apps/builder/generate_app_variables.sh; DO NOT EDIT.
# Make changes to the template in ./modules/apps/builder/generate_app_variables.sh

variable "cluster" {
  type = object({
    path          = string
    cmd_start     = string
    cmd_update    = string
    cmd_stop      = string
    cmd_deploy_fn = string
  })
}

variable "services" {
  type = list(object({
    image             = string
    name              = string
    restart           = string
    environment       = list(string)
    networks          = list(string)
    command           = list(string)
    stop_grace_period = string
    entrypoint        = optional(list(string))
    working_dir       = optional(string)
    healthcheck       = optional(map(string))
    ports             = list(string)
    volumes           = list(object({ mount_name = optional(string), container_path = string, abs_host_path = optional(string) }))
    configs           = list(object({ config_file = string, destination = string, content = optional(string) }))
  }))

  validation {
    condition     = length(var.services) > 0
    error_message = "At least one service must be defined"
  }

  validation {
    condition = (
      length([for s in var.services : s.name if length(s.name) > 0]) ==
      length(var.services)
    )
    error_message = "All services must have a name"
  }

  validation {
    condition = (
      length([for s in var.services : s.name if length(s.name) > 0]) ==
      length(toset([for s in var.services : s.name if length(s.name) > 0]))
    )
    error_message = "All services must have a unique name"
  }
}
